<!-- <h2>Automatic Slideshow</h2>
<p>Change image every 2 seconds:</p>

<div class="slideshow-container"> -->

<div class="mySlides fade">
  <div class="numbertext">1 / 3</div>
  <img src="<?php echo $this->getViewFileUrl('Chetu_Himanshu::images/crsl1.png'); ?>" style="width:100%">
  <div class="text">Caption Text</div>
</div>

<div class="mySlides fade">
  <div class="numbertext">2 / 3</div>
  <img src="<?php echo $this->getViewFileUrl('Chetu_Himanshu::images/crsl2.png'); ?>" style="width:100%">
  <div class="text">Caption Two</div>
</div>

<div class="mySlides fade">
  <div class="numbertext">3 / 3</div>
  <img src="<?php echo $this->getViewFileUrl('Chetu_Himanshu::images/crsl3.png'); ?>" style="width:100%">
  <div class="text">Caption Three</div>
</div>

</div>
<br>

<div style="text-align:center">
  <span class="dot"></span> 
  <span class="dot"></span> 
  <span class="dot"></span> 
</div>